package TopCoder;

public class SequenceOfCommands {

	public static void main(String[] args) {
		String[] commands = {"LSRSLLRRSLLSSSRRRRRLRSLRLLLSLLLLLSRSSRRLRLRSRRSSRL", "RLLSLRSRLRRRLRLSSSRRRRRLRRLSRSRRLSSSLRSLRLRLSRRSRS", "RRSLRLRRLSLLRRRLRSRRRRRSRRSRSRSSSSRLRRRRRLSLSRLLLR", "LRRSRRSSRRLSRRLRRRRLRRRLRSRLRRLSRSLRRSSRRSSRSRRRSS", "SRRLSLRRSRRLRSLRLRLSSLLSLLRRSSRLRRSRLRLSSSLSRSRLSS", "SRLRRSSRLRSSRSRSLRLRRRRSRRLLLSRRLRRRRRRRRRLLRRSRSL", "RRLLLRLLRRSLSSLRRLRRRRRRSRRRSRRSRRRSRRLRLRSLLSLSRR", "SLRLRLSRSRLLRRSSLRSLLRLLSRSRRRRSSLRLSLLRSLRRRSLLLS", "RRLRSRRLRLRRSSSRLRRLLRLRRRRRRSRSRLRRSRRRSRRRSLLRRR", "RLLLSSLRRRSSRSRSLLRLLSSSSRSRRRSLRRRSLLLSRSRRLLRLSR", "LSSLSRLRRRLSSLSRRRRSRRLRRSLRSSLLLSRRSRRSRRSRRSLSRL", "SRRRLSSLRSLRRRLLLLRRRLLLLRLLSRRRLRRLSRLLRLLRSLLSLR", "RLSRRSLRLSSLRRSLRRRRLSLSSLLRLLSRLRRSSSRLRRLRLRSSRL", "SLSRRSLRLLRRLLRLLRSLRRLSRLRRLRLRRRLRRRSLRRSRRSRLRS", "SRRRRSRRRLRRRRRLRRRSRLSLRSRLRSRRRRRRSRRSRSSLSRLRRS", "SLRRSRLRSRSRLSLSSRRRRLRSLRRRRSLRRLRLSRRSRSSSRRRLLR", "RRLLRRRRSRRRRLRLRSSLLSRRRSLSLLSRRRRSSSRSLLSRRRRRRR", "SRRSRRRRSSSLLSLRRLLRSRRRRRRSRRLRSRLLLRSRLRSLRRRRRS", "LRSLRRSRLRRRSLRRLRRSRSLRSRLLLRSLLSSRLRLRLLRLSSRLRR", "RSSSLRSRSSRLRRLLSRLRSSRRRRRLLLRRSRRSRRRSRRSLSSLRRS", "SRLSSLLLLRRLLRRLRLRSSRRSSSLLLRSLRRSSSRRRSSLLRRLRSR", "LRRLLLRSRRLLSRSLRLRLSRSLSSLRRRRRRRSSRRRSRRLSLLLRRL", "LSSSRRSSLRRRRRRRSSRSRSSLLRRRRRSRRLSRLSLLSLLRRLRRRL", "SLLSLRRRSSRSLSLRSRRLRRSLRLSRRRLSLRLRRSRRLRRRLRLRLR", "LLLSRSSRSRRSRLRLSRRLLRSRSSRLRRSSSRLLLLRRRSSRLLRRSL", "RRRRLRSRLRRLSRSSSSSRLSRSSRLRRSRLSSSRRLRLRSRRLSRRRL", "LRRRRSSLLRRLSRSSRRSRSLRSSRSRLRLLLRLSRRRRSSRLRRRLSR", "RLSRLRRRLLLSLRRSSSSSLRSRRSSSRRLSRRLLRRSSRRSRSRSSRS", "RLSRLSSSSRRRLSLRRLLSLRRSSRSRRRSLRRSSRLRSRRSRSRLSRR", "RSSRRLLRRLRSRRRRRSRSSSRRLSSRRRSSRRSRLRRSLRRLSRSSRR", "RLSLSLRLLRLLSSRLLRRSRSRRRRRRSRRRSRRRRRLRRRLLLSSRRR", "RRLLRRRRRRRRRRSLRRSRRLLSRLSLLLLLSSRLLRLLSRRRSRRRLS", "RRRRRSRSLRLSSSSLLRLSRLRRRLSLSSRSSRSLRRRSLRSRRSRRSR", "RRSSLSLLRSLRSRRRLRRLLLSLLRLSRRSLLRRLLRLRRRSSRLLSRL", "LRLSSLSRRSRRSSSSSLLRRSSRLLRSRRLLSSRLRLSRRRLLLRLRRS", "SLLSRRSSLLSSLLSRRRLRRLRRRRRLRRSRLRRSRRSRLRSLRSRSLS", "LRLLRRSLRLRLSSLLRRSSLRSRRSRRRRLLSSRRRSLRRSLRLLLRRS", "LLSLSLRRRSRSSSSRRSRRSSRRRSRRLSSSRLLLRRSRLLRRRLRRRR", "LRLSLRLLLSRRRRLLRSSRSRSRSSLLRSRSRLRSRLLLLLRRRRSRRR", "RRLRRSLRLRLSRRSRRSLSRRSLRRRSRRSLSLSRRRLRRRSRSRRLRL", "LRRRRRLSRRRSLRRSRRRLLSRLRRSRRRLLL"}	
		;
		String res = whatHappens(commands);
		System.out.println(res);

	}

	public static String whatHappens(String[] commands) {
		int x = 0;
		int y = 0;
		int d = 0;
		int[] dx = {1,0,-1,0};
		int[] dy = new int[]{0,1,0,-1};
		for (int i = 0; i < 4; i++) {
			for(String s: commands){
				for (int k = 0; k < s.length(); k++) {
					char c = s.charAt(k);
					if (c=='L') d = (d+3)%4;
					if (c=='R') d = (d+1)%4;
					if (c=='S'){
						x+=dx[d];
						y+=dy[d];
					}
				}
			}
		}
		if (x==0 && y ==0) return "bounded";
		else return "unbounded";
	}
}